temp_dir: '/tmp/'
segment_prefix: 'sample'
index_prefix: 'stream'

# type of logging: STDOUT, FILE
log_type: 'STDOUT'
#log_type: 'FILE'
#log_file: '/tmp/streamer.log'
# levels: DEBUG, INFO, WARN, ERROR
log_level: 'DEBUG'

# where the origin video is going to come from
input_location: 'http://localhost:8080/'

# segment length in seconds
segment_length: 10 

# this is the URL where the stream (ts) files will end up
# if this location is the same as the location where the m3u8 
# index is then leave it blank
# url_prefix: ''
url_prefix: 'http://192.168.1.1/streamingvideo/'

# how many segments to keep in the index
index_segment_count: 15

# this command is used for multirate encodings and is what pushes the encoders
source_command: 'ffmpeg -er 4 -y -i %s -vcodec copy -acodec copy -f ogg -'

# This is the location of the segmenter
segmenter_binary: './live_segmenter'

# the encoding profile to use
encoding_profile: [ 'ep_192k', 'ep_348k', 'ep_576k' ]

# The upload profile to use
transfer_profile: 'copy_dev'

#
# Encoding profiles
#
ep_192k:
  ffmpeg_command: "ffmpeg -er 4 -y -i %s -f mpegts -acodec libmp3lame -ab 64k -vf scale=320:240 -vcodec libx264 -threads 0 -preset fast -b 128k -maxrate 128k -bufsize 128k -g 30 -async 2 - | %s %s %s %s %s"
  bandwidth: 192000

ep_348k:
  ffmpeg_command: "ffmpeg -er 4 -y -i %s -f mpegts -acodec libmp3lame -ab 96k -vf scale=320:240 -vcodec libx264 -threads 0 -preset fast -b 256k -maxrate 256k -bufsize 256k -g 30 -async 2 - | %s %s %s %s %s"
  bandwidth: 348000

ep_576k:
  ffmpeg_command: "ffmpeg -er 4 -y -i %s -f mpegts -acodec libmp3lame -ab 128k -vf scale=320:240 -vcodec libx264 -threads 0 -preset fast -b 448k -maxrate 448k -bufsize 448k -g 30 -async 2 - | %s %s %s %s %s"
  bandwidth: 576000

#
# Transfer profiles
#
s3_dev:
  transfer_type: 's3'
  bucket_name: 'bucket'
  key_prefix: 'stream0001'
  aws_api_key: 'key'
  aws_api_secret: 'secret'

ftp_dev:
  transfer_type: 'ftp'
  remote_host: '192.168.1.1'
  user_name: 'user'
  password: 'pass'
  directory: 'html/streamingvideo'

## Multiple ftp server example:
multi_ftp_dev:
  transfer_type: 'ftp'
  remote_host: ['first-server.com', 'second-server.com']
  user_name: ['firstserveruser', 'seconduserserver']
  password: ['firstserverpass', 'secondserverpass']
  directory: ['first/server/dir', 'second/server/dir']
### If the remote_host is an array, all the other (user_name, password, directory) has to be arrays to, and has to have the same item number as the remote_host array, else it won't work and bad things will happen!

scp_dev:
  transfer_type: 'scp'
  remote_host: '192.168.1.1'
  user_name: 'root'
  #password: 'pass'
  directory: '/web/sites/test.com/html/streamingvideo'

copy_dev:
  transfer_type: 'copy'
  directory: '/var/www/html/streamingvideo'
  
cf_dev:
  transfer_type: 'cf'
  container: 'container'
  username: 'username'
  api_key: 'api_key'
  key_prefix: 'stream0001'
  